#ifndef AES256_DEFINES_H
#define AES256_DEFINES_H

#include <windows.h>

// BCRYPT
#define BCRYPTOPENALGORITHMPROVIDER 0x3e8576bd
#define BCRYPTCLOSEALGORITHMPROVIDER 0xef8885e7
#define BCRYPTENCRYPT 0x3ea12744
#define BCRYPTDECRYPT 0xfb8806a0
#define BCRYPTDESTROYKEY 0xdad6b776
#define BCRYPTGENERATESYMMETRICKEY 0xcc7d94fa
#define BCRYPTSETPROPERTY 0xaccf8fa8
#define BCRYPTGETPROPERTY 0x5ae4b8f4

// BCRYPT
typedef NTSTATUS (WINAPI *_BCRYPTOPENALGORITHMPROVIDER)(BCRYPT_ALG_HANDLE *phAlgorithm, LPCWSTR pszAlgId, LPCWSTR pszImplementation, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTSETPROPERTY)(BCRYPT_ALG_HANDLE hObject, LPCWSTR pszProperty, PUCHAR pbInput, ULONG cbInput, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTGETPROPERTY)(BCRYPT_ALG_HANDLE hObject, LPCWSTR pszProperty, PUCHAR pbOutput, ULONG cbOutput, ULONG *pcbResult, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTGENERATESYMMETRICKEY)(BCRYPT_ALG_HANDLE hAlgorithm, BCRYPT_KEY_HANDLE *phKey, PUCHAR pbKeyObject, ULONG cbKeyObject, PUCHAR pbSecret, ULONG cbSecret, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTENCRYPT)(BCRYPT_KEY_HANDLE hKey, PUCHAR pbInput, ULONG cbInput, VOID *pPaddingInfo, PUCHAR pbIV, ULONG cbIV, PUCHAR pbOutput, ULONG cbOutput, ULONG *pcbResult, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTDECRYPT)(BCRYPT_KEY_HANDLE hKey, PUCHAR pbInput, ULONG cbInput, VOID *pPaddingInfo, PUCHAR pbIV, ULONG cbIV, PUCHAR pbOutput, ULONG cbOutput, ULONG *pcbResult, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTCLOSEALGORITHMPROVIDER)(BCRYPT_ALG_HANDLE hAlgorithm, ULONG dwFlags);
typedef NTSTATUS (WINAPI *_BCRYPTDESTROYKEY)(BCRYPT_KEY_HANDLE hKey);

// BCRYPT
extern _BCRYPTOPENALGORITHMPROVIDER _BCryptOpenAlgorithmProvider;
extern _BCRYPTSETPROPERTY _BCryptSetProperty;
extern _BCRYPTGETPROPERTY _BCryptGetProperty;
extern _BCRYPTGENERATESYMMETRICKEY _BCryptGenerateSymmetricKey;
extern _BCRYPTENCRYPT _BCryptEncrypt;
extern _BCRYPTDECRYPT _BCryptDecrypt;
extern _BCRYPTCLOSEALGORITHMPROVIDER _BCryptCloseAlgorithmProvider;
extern _BCRYPTDESTROYKEY _BCryptDestroyKey;

#endif //AES256_DEFINES_H
