#ifndef BASE64_DEFINES_H
#define BASE64_DEFINES_H

#include <windows.h>

#define WINHTTP_FLAG_SECURE                 0x00800000
#define WINHTTP_ACCESS_TYPE_DEFAULT_PROXY   0
#define WINHTTP_NO_PROXY_NAME               NULL
#define WINHTTP_NO_PROXY_BYPASS             NULL
#define WINHTTP_NO_REFERER                  NULL
#define WINHTTP_DEFAULT_ACCEPT_TYPES        NULL

typedef WORD INTERNET_PORT;
typedef INTERNET_PORT *LPINTERNET_PORT;
typedef LPVOID HINTERNET;
typedef HINTERNET *LPHINTERNET;
typedef int INTERNET_SCHEME, *LPINTERNET_SCHEME;
typedef struct {
    DWORD   dwStructSize;
    LPWSTR  lpszScheme;
    DWORD   dwSchemeLength;
    INTERNET_SCHEME nScheme;
    LPWSTR  lpszHostName;
    DWORD   dwHostNameLength;
    INTERNET_PORT nPort;
    LPWSTR  lpszUserName;
    DWORD   dwUserNameLength;
    LPWSTR  lpszPassword;
    DWORD   dwPasswordLength;
    LPWSTR  lpszUrlPath;
    DWORD   dwUrlPathLength;
    LPWSTR  lpszExtraInfo;
    DWORD   dwExtraInfoLength;
} URL_COMPONENTS, *LPURL_COMPONENTS;

// WINHTTP
#define WINHTTPOPEN 0xaebc83a5
#define WINHTTPCONNECT 0xb0b51a4d
#define WINHTTPOPENREQUEST 0x1552df72
#define WINHTTPSENDREQUEST 0xe0cfb564
#define WINHTTPRECEIVERESPONSE 0xec3c8021
#define WINHTTPQUERYDATAAVAILABLE 0x26088ae6
#define WINHTTPREADDATA 0x943a5129
#define WINHTTPCLOSEHANDLE 0xd2053a99
#define WINHTTPCRACKURL 0xa7f145b6

//KERNEL32
#define MULTIBYTETOWIDECHAR 0x9053f9c2


// WINHTTP
typedef HINTERNET (WINAPI *_WINHTTPOPEN)(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD);
typedef HINTERNET (WINAPI *_WINHTTPCONNECT)(HINTERNET, LPCWSTR, INTERNET_PORT, DWORD);
typedef HINTERNET (WINAPI *_WINHTTPOPENREQUEST)(HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR *, DWORD);
typedef BOOL (WINAPI *_WINHTTPSENDREQUEST)(HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD, DWORD, DWORD_PTR);
typedef BOOL (WINAPI *_WINHTTPRECEIVERESPONSE)(HINTERNET, LPVOID);
typedef BOOL (WINAPI *_WINHTTPQUERYDATAAVAILABLE)(HINTERNET, LPDWORD);
typedef BOOL (WINAPI *_WINHTTPREADDATA)(HINTERNET, LPVOID, DWORD, LPDWORD);
typedef BOOL (WINAPI *_WINHTTPCLOSEHANDLE)(HINTERNET);
typedef BOOL (WINAPI *_WINHTTPCRACKURL)(LPCWSTR, DWORD, DWORD, LPURL_COMPONENTS);

// KERNEL32
typedef int (WINAPI *_MULTIBYTETOWIDECHAR)(UINT CodePage,DWORD dwFlags,LPCCH lpMultiByteStr,int cbMultiByte,LPWSTR lpWideCharStr,int cchWideChar);

//WINHTTP
extern _WINHTTPOPEN _WinHttpOpen;
extern _WINHTTPCONNECT _WinHttpConnect;
extern _WINHTTPOPENREQUEST _WinHttpOpenRequest;
extern _WINHTTPSENDREQUEST _WinHttpSendRequest;
extern _WINHTTPRECEIVERESPONSE _WinHttpReceiveResponse;
extern _WINHTTPQUERYDATAAVAILABLE _WinHttpQueryDataAvailable;
extern _WINHTTPREADDATA _WinHttpReadData;
extern _WINHTTPCLOSEHANDLE _WinHttpCloseHandle;
extern _WINHTTPCRACKURL _WinHttpCrackUrl;

// KERNEL32
extern _MULTIBYTETOWIDECHAR _MultiByteToWideChar;

#endif //BASE64_DEFINES_H
